language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull areyouok/redis-sentinel
  - docker pull areyouok/redis-cluster
  - docker run -d -p 6379-6381:6379-6381 -p 26379-26381:26379-26381 areyouok/redis-sentinel
  - docker run -d --net=host areyouok/redis-cluster
#services:
#  - redis-server
#script: "mvn cobertura:cobertura"
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#before_install:
#  - pip install --user codecov
#after_success:
#  - codecov
